### ISSUE TITLE
[FEATURE] Linux + Psi + OMEMO

### ISSUE THREAD

**Issue by alexandre1985** [psi-im/plugins#104]
When will psi-plugins support OMEMO for Linux?
My machine as a ArchLinux OS.
(I am not talking about Psi+, which already supports OMEMO in psi-plus-plugins)

**Comment by tehnick** [comment]
As written in [CHANGELOG](https://github.com/psi-im/psi/blob/master/CHANGELOG) Psi v2.0 will be the first release of Psi with OMEMO support. Psi+ is a development version of Psi, that is why it already has OMEMO plugin...
