### ISSUE TITLE
Skins plugin is needed

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#105]
Add again Skins plugin, people want it:
- https://github.com/psi-im/plugins/tree/master/deprecated/skinsplugin

Thanks in advance.

**Comment by Vitozz** [comment]
Fixed in 1fb5a47d389f5b75fb01745a25c94e1297e0f599

**Comment by Neustradamus** [comment]
@Vitozz: Thanks for your work, I will try soon with the next build :)
