### ISSUE TITLE
Plugins settings button messed up

### ISSUE THREAD

**Issue by pztrn** [psi-im/plugins#23]
When I pressed configuration button for gpg plugin - settings dialog for extended preferences plugin opened:

<img width="1680" alt="2017-06-11 14 00 20" src="https://user-images.githubusercontent.com/869402/27009735-199d864a-4eaf-11e7-9244-42a0ef06dc82.png">

I'm on latest Psi and Psi+  (psi-im/psi@a3fb596758192ec1d3ce0f741ced9a1fba021249 for Psi and 6ed09dad3f132fd34829b9571d08d0d6591cb528 for plugins)

**Comment by wadealer** [comment]
Yes, I already know about this issue. Settings button opens dialog for the plugin above. It's present on Mac only. I'll try to fix this as soon as I have some free time.

**Comment by wadealer** [comment]
Fixed with commit https://github.com/psi-im/psi/commit/e1889b2a8faf7000fdc4ce75a2828d8400598d81
