### ISSUE TITLE
OMEMO : Please add "Clear devices" and "Refresh" buttons in "Manage Devices"

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#38]
It will be nice to have in "Manage Devices":
- "Clear devices" button for remove (old) not connected XMPP OMEMO clients
- "Refresh" button for have actual list of XMPP OMEMO clients

**Comment by tehnick** [comment]
> "Refresh" button for have actual list of XMPP OMEMO clients

It is not required. All should be updated automatically, see:
https://xmpp.org/extensions/xep-0384.html#usecases-announcing

**Comment by Neustradamus** [comment]
@tehnick said that it is auto-refreshed.

To confirm:
1/ Open Psi -> Options -> Plugins -> Settings of OMEMO plugin -> Own Keys
2/ Do not close the window
3/ Launch the same XMPP account in a new device, and you must to see the new device automatically, if not, the problem is always here

**Comment by Neustradamus** [comment]
@tehnick: I have done a test!
I can confirm that there is an auto-refresh!
The new device is added but without the fingerprint.

Can you solve it?

Thanks in advance.
