### ISSUE TITLE
Client Switcher Plugin prevents normal usage of OMEMO Plugin and PEP features

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#50]
Today, I have spoken with a guy for the first time, there was a problem with OMEMO.

I have the Client Switcher plugin and OMEMO plugin enabled:
*** [OMEMO] Unable to build any sessions, the message was not sent

I have disabled the Client Switcher plugin, it is ok, I have enabled a new time the Client Switcher plugin after.

Please note that there is always the big problem of grey OMEMO icon too...

**Comment by tehnick** [comment]
Done.

**Comment by Neustradamus** [comment]
You can do, @Ri0n said me that it was impossible to move.

**Comment by tehnick** [comment]
> @Ri0n said me that it was impossible to move.

It was outdated information.

**Comment by Neustradamus** [comment]
I have disabled the plugin for have new OMEMO keys from contacts...
It is not only for new discussions, but for all.

**Comment by l-n-s** [comment]
Copying a bug report from our conference, as is, it might be useful:

> ‎[12:16:18 PM] ‎Nekun‎: в общем, по какой-то причине омемо-плагин в пси не дружит с клиент свитчер-плагином
> ‎[12:16:55 PM] ‎Nekun‎: 1. омема не включается, если клиент-свитчер настроен на единый профиль для всех аккаунтов
> ‎[12:17:39 PM] ‎Nekun‎: 2. омема включается только при переподключении, если клиент-свитчер настроен на индивидуальный профиль для каждого акка
> ‎[12:18:48 PM] ‎Nekun‎: 3. сам этот плагин какое-то ебаное решето, судя по тому что при подключении в ростере рядом с собственным акком ненадолго мигает иконка нашего UA

**Comment by Neustradamus** [comment]
In more:
- Extended Options Plugin -> Roster -> Tooltips -> Show geolocalisation does not work

**Comment by tehnick** [comment]
Now there is special label with warning in Client Switcher Plugin options dialog window.

**Comment by Neustradamus** [comment]
@tehnick: Yes an update will be perfect with solution.
Please do not close an unsolved ticket.
