### ISSUE TITLE
[OMEMO] encrypted files can't recieve...

### ISSUE THREAD

**Issue by wkg** [psi-im/plugins#51]
files from conversations encrypted with omemo, i can't receive in psi,
files come as url like "aesgcm://.....", please add at least i can recieve...

**Comment by tehnick** [comment]
Which version of Psi do you use?

**Comment by wkg** [comment]
Psi+ v1.4.705 (2019-05-31, Psi:dea7fcb3, Psi+:280e8c3)

**Comment by wkg** [comment]
plagins  from https://github.com/psi-im/plugins.git "master" branch

**Comment by tehnick** [comment]
Ok, I see. I have just checked: in Psi+ v1.4.554 it works fine.

It looks like recent changes in `iris` library broke more than we have found in https://github.com/psi-im/psi/issues/349#issuecomment-490584434

@Ri0n Any forecasts when that regression may be fixed?

**Comment by wkg** [comment]
in Psi v1.4-dev-20190531 it work...

**Comment by Ri0n** [comment]
@tehnick, when I done with Jingle. rather soon.

**Comment by tehnick** [comment]
Works fine in latest versions of Psi+.

**Comment by Neustradamus** [comment]
@Ri0n: Do you recall the problem that we had somes weeks ago?
It is not solved completely no?
