### ISSUE TITLE
[OMEMO] Encryption of files sending via HTTP File Upload

### ISSUE THREAD

**Issue by antranigv** [psi-im/plugins#53]
Hi all!

I downloaded the new version of Psi+, which is based on Psi, and for some reason the HTTP file upload plugin was missing. after some digging I saw that the plugin is now deprecated in Psi.

Is there a reason for that? how are we supposed to 1) send files now? 2) send OMEMO encrypted files?

thanks in advance! :)

**Comment by Ri0n** [comment]
ctrl+v or drag'n'drop on chat dialog would upload a file via http when it's available.
regarding omemo encrypted I didn't really test it after all the changes but people say it doesn't work. I'll review this when have some time for that

**Comment by tehnick** [comment]
> Is there a reason for that?

This function was moved from plugin to program core.

> send OMEMO encrypted files?

This feature was not implemented in the core yet.

**Comment by tehnick** [comment]
Moved to #84
