### ISSUE TITLE
OMEMO is forcing: *** [OMEMO] Unable to build any sessions, the message was not sent

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#54]
A contact has not OMEMO (it is specified by the client), the OMEMO icon is in grey and the mouse on it says:
- OMEMO is not available for this contact

When we send a message to a contact, it is forced by OMEMO (not unencrypted message):
- *** [OMEMO] Unable to build any sessions, the message was not sent

There is no possibility to send unencrypted messages in the chat window of the contact, the icon is in grey and disabled.

Right click on our account in roster -> XML Console -> JID -> the contact@domain.tld
-> enable checked

Result for a sent message: Nothing, it is empty.

There is no OMEMO fingerprint for this contact in the client -> Options -> Plugins -> OMEMO plugin -> Fingerprints

**Comment by ortuman** [comment]
To give more context, from server PoV no XMPP payload is received at all. So whatever is going on, seems it only occurs on client side.

**Comment by Neustradamus** [comment]
@stigger: Any news about this historical OMEMO bug?

I am very good, I have done a screenshot only for you:
- https://i.ibb.co/zZX9XRZ/psi-omemo-plugin-problem-is-not-available-for-this-contact-grey-icon-and-unable-to-build-any-sessions-the-mesage-was-not-sent.png

Problem: Grey icon, OMEMO is automatically forced, impossible to disable OMEMO for this contact.

**Comment by Neustradamus** [comment]
@tehnick: I confirm that the bug is always here with your last build:
- Psi+ 1.4.1303 (2020-05-27, Psi:f34443ba, Psi+:2170e90)

- *** [OMEMO] Unable to build any sessions, the message was not sent
- Grey icon
- Impossible to disable forced OMEMO messages

**Comment by Neustradamus** [comment]
@kssytsrk: Can you look this ticket?

**Comment by kssytsrk** [comment]
Might this be a result of Options > Plugins > OMEMO plugin settings > Configuration > OMEMO encryption policy being set to "Always enabled"? I have it set to "Disabled by default", and can't reproduce on Psi+ 1.5.1551 (2021-08-16) / FreeBSD 13.0.

**Comment by Neustradamus** [comment]
I have "Disabled by default".

**Comment by Neustradamus** [comment]
@kssytsrk: Thanks for your reply.

Can you test with 2 new test accounts without OMEMO used before?

Please use Psi+ and Psi+.

You will find the problem...

**Comment by Neustradamus** [comment]
@tehnick: Example of the problem today with a roster contact who does not have/use OMEMO:

In tab, the OMEMO icon is in grey "OMEMO encryption is not available for this contact".

When I send a simple message, it is OMEMO forced, no possibility to change it...
[XX:XX:XX] *** [OMEMO] Unable to build any sessions, the message was not sent
[XX:XX:XX] <Neustradamus> Test

```
<iq id='XXXXXX' from='me@domain.tld' to='contact@domain.tld' type='get'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<items node='eu.siacs.conversations.axolotl.devicelist'/>
</pubsub>
</iq>

<iq type="result" from="contact@domain.tld" to="me@domain.tld/client" id="XXXXXX">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.devicelist">
<item id="current">
<list xmlns="eu.siacs.conversations.axolotl">
<device id="XXXXXXXXX"/>
<device id="XXXXXXXXXX"/>
</list>
</item>
</items>
</pubsub>
</iq>
```

I have the same problem with the same contact in a no-anonymous MUC Room and 1:1 PM messages disabled.

**Comment by Neustradamus** [comment]
@nullobsi: I have this problem with you in the client...
