### ISSUE TITLE
[OMEMO] Keys icon in Roster near Username is not showed before a message after each Psi launch

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#66]
Keys icon in Roster near Username is not showed all time.

At each Psi launch, we need to send a message to see it.

**Comment by tehnick** [comment]
Unlike OTR, OMEMO protocol does not have mechanisms for indication of current state of chat. In simple words: you know that OMEMO encryption is enabled only after receiving of first encrypted message.

**Comment by Neustradamus** [comment]
@Ri0n, @tehnick, @stigger: I think it is possible to add the key icon at connection, when the client detect the node of contacts:
`eu.siacs.conversations.axolotl.devicelist`
