### ISSUE TITLE
[OMEMO] Problem if a new roster contact has not OMEMO and the contact enables OMEMO in the talk

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#67]
Add a new roster contact

> [XX:XX:XX] <user@domain.tld> Normal message

Not a message, indication for this bug: OMEMO icon is in grey: "OMEMO encryption is not available for this contact"

> [XX:XX:XX] <me> Can you send me OMEMO message?
> [XX:XX:XX] *** [OMEMO] The following message is from an untrusted device:
> [XX:XX:XX] ***  Encryption Enabled
> [XX:XX:XX] <user@domain.tld> OMEMO message test

Not a message, indication for this bug: OMEMO icon is always in grey: "OMEMO encryption is not available for this contact".

> [XX:XX:XX] *** [OMEMO] Unable to build any sessions, the message was not sent
> [XX:XX:XX] ***  Encryption Enabled
> [XX:XX:XX] <me> reply 1

Not a message, indication for this bug: OMEMO icon is always in grey: "OMEMO encryption is not available for this contact", and I can not disable forced OMEMO.

> [XX:XX:XX] *** [OMEMO] Unable to build any sessions, the message was not sent
> [XX:XX:XX] <me> reply 2

Not a message, indication for this bug: OMEMO icon is always in grey: "OMEMO encryption is not available for this contact", and I can not disable forced OMEMO.

Note 1: In Roster, I see "Keys" icon near username of this contact.
Note 2: I have not closed the tab since the first normal message.

Linked to:
- https://github.com/psi-im/plugins/issues/54

**Comment by tehnick** [comment]
Fixed in Psi+ 1.4.1300 and newer.

**Comment by Neustradamus** [comment]
This problem is always here.

**Comment by Neustradamus** [comment]
There is a new PR which can solves it:
- https://github.com/psi-im/plugins/pull/106
