### ISSUE TITLE
[OMEMO] Plugin options window is little small (7/8 of the fingerprint on one line, last 1/8 on second line)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#68]
OMEMO plugin: Options window is little small (7/8 of the fingerprint on one line, last 1/8 on second line)
- https://i.ibb.co/bPzZyhZ/psi-default-window-size-plugins-omemo-problem.png

Better to have only one line.

**Comment by tehnick** [comment]
Just resize the window.

**Comment by Neustradamus** [comment]
The window size is always the default size, it is better to change in code.

**Comment by tehnick** [comment]
> The window size is always the default size

What should it mean?

**Comment by Neustradamus** [comment]
When we close the window, and when we reopen it, it is default size.

Can you update the window size directly in the code?

**Comment by tehnick** [comment]
Fixed
