### ISSUE TITLE
[OMEMO] Empty fingerprint request window

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#70]
We can receive for a contact, an empty fingerprint request, this problem is not new:
- https://i.ibb.co/wgrzN4N/psi-plus-omemo-empty-fingerprint-request.png
- https://i.ibb.co/nfSbjyG/psi-omemo-empty-fingerprint-request-2020.png

**Comment by tehnick** [comment]
36b992f7cf962d576525822dbfc1741e42337f40
