### ISSUE TITLE
[Stop Spam] View Log window "\" instead of "/" and without Minimize and Maximize buttons

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#73]
Options -> Plugins -> Settings of Stop Spam -> Misc -> View Log
- `\` instead of `/`
- Without Minimize and Maximize buttons

-> https://i.ibb.co/K6tbnx3/psi-stop-spam-plugin-view-log-window.png

**Comment by tehnick** [comment]
6f2bbdc05bd724182e543ca2cdee8aa917ce9f8f

**Comment by Neustradamus** [comment]
@tehnick: Thanks!

After your changes, I have looked, it is not possible to have the good link on Windows?
-> C:\Users\USERNAME\AppData\Roaming\Psi+\profiles\Blockedstanzas.log

Same for Conference Logger plugin and Client Switcher.

Yes, only the separator was good on Windows.

**Comment by tehnick** [comment]
Read commit changes attentively.
