### ISSUE TITLE
[Windows] Minimize/Maximize buttons are missing for "Client Switcher" / "Conference Logger" / "Stop Spam" View Log window

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#74]
Minimize/Maximize buttons are missing for:
- Options -> Plugins -> Settings of Client Switcher -> Logs -> View log
- Options -> Plugins -> Settings of Conference Logger -> View Log
- Options -> Plugins -> Settings of Stop Spam -> Misc -> View Log

-> https://i.ibb.co/wWL2pYn/psi-muc-room-history-window-missing-min-max-buttons.png
-> https://i.ibb.co/K6tbnx3/psi-stop-spam-plugin-view-log-window.png

Linked to:
- https://github.com/psi-im/psi/issues/122
- https://github.com/psi-plus/main/issues/642

**Comment by tehnick** [comment]
MS Windows specific

**Comment by tehnick** [comment]
> Options -> Plugins -> Settings of Stop Spam -> Misc -> View Log

6f2bbdc05bd724182e543ca2cdee8aa917ce9f8f

**Comment by tehnick** [comment]
0f3a325bdcfb180cc3ddf9320daa1f483bd3a6d1
278f93aac5ed9682a0975bac846c3ff3b79b88ba

**Comment by Neustradamus** [comment]
@Tehnick: After several years, thanks!
