### ISSUE TITLE
[OTR] Settings like OMEMO plugin

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#76]
Can you do OTR settings improvements?
- Accounts in scrolling menu instead of "Account" column
- Move "Verified" and "Status" before Fingerprint column

Screenshots:
- https://i.ibb.co/Tcp2dQK/psi-omemo-settings.png
- https://i.ibb.co/tBM0tXc/psi-otr-settings.png

And:
- If a fingerprint is verified: "Trusted" (Currently "verified")
- If a fingerprint is verified but not accepted: "Untrusted" (Currently nothing)
- If a fingerprint is not verified: "Undecided" (Currently nothing)

**Comment by tehnick** [comment]
wontfix
