### ISSUE TITLE
[OMEMO] Change "Trust" to "Verified" in table part + Trusted / Untrusted / Undecided

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#77]
Can you change "Trust" to "Verified" in column name?

Screenshots:
- https://i.ibb.co/Tcp2dQK/psi-omemo-settings.png
- https://i.ibb.co/tBM0tXc/psi-otr-settings.png

And:
- If a fingerprint is verified: "Trusted" (Currently "trusted")
- If a fingerprint is verified but not accepted: "Untrusted" (Currently "untrusted")
- If a fingerprint is not verified: "Undecided" (Currently "not decided")

**Comment by tehnick** [comment]
OTR != OMEMO

wontfix
