### ISSUE TITLE
[OpenPGP] Settings like OMEMO plugin

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#78]
Can you do OpenPGP settings improvements?
- Add number column before "User" column
- Accounts in scrolling menu instead of "Account" column

Screenshots:
- https://i.ibb.co/Tcp2dQK/psi-omemo-settings.png
- https://i.ibb.co/VLRRJKH/psi-openpgp-settings.png

**Comment by Ri0n** [comment]
part?

**Comment by Neustradamus** [comment]
Scrolling menu instead of Account part (see screenshot)
Number part (see screenshot)

**Comment by Ri0n** [comment]
do you mean "column"?

**Comment by Neustradamus** [comment]
Yes sorry.

**Comment by tehnick** [comment]
wontfix

OpenPGP plugin settings dialog is perfect now.

Moreover, settings dialog of OMEMO plugin should be updated instead. To looks like the one in OpenPGP and OTR plugins.
