### ISSUE TITLE
1.5 plugins tag is not good

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#88]
1.5 plugins tag is not good, can you solve it?
- https://github.com/psi-im/plugins/releases/tag/1.5
- https://github.com/psi-im/plugins/releases/tag/1.4

**Comment by Neustradamus** [comment]
Note: It is same for psi-l10n and issues section is not opened:
- https://github.com/psi-im/psi-l10n/releases/tag/1.5
- https://github.com/psi-im/psi-l10n/releases/tag/1.4

**Comment by Neustradamus** [comment]
When we look the 1.5 release date: 6 Sep 2020, it must be, tags must be:
- plugins: https://github.com/psi-im/plugins/commit/c430f74e2e0063ece73e4bcd5ce0430d7259e050
- psi-l10n: https://github.com/psi-im/psi-l10n/commit/c40f71d17d61fa493058975e11d96aa1f6793b14

Thanks in advance.

**Comment by tehnick** [comment]
You are wrong.

**Comment by Neustradamus** [comment]
plugins:
@ValdikSS tagged this on 5 Nov 2018 · 356 commits to master since this tag
- https://github.com/psi-im/plugins/releases/tag/1.5

@Ri0n Ri0n tagged this on 5 Nov 2018 · 356 commits to master since this tag
- https://github.com/psi-im/plugins/releases/tag/1.4

Same 1.4 and 1.5.

------------

psi-l10n:
@tehnick tehnick tagged this on 6 Nov 2018 · 36 commits to master since this tag
- https://github.com/psi-im/psi-l10n/releases/tag/1.5

@tehnick tehnick tagged this on 6 Nov 2018 · 36 commits to master since this tag
- https://github.com/psi-im/psi-l10n/releases/tag/1.4

Same 1.4 and 1.5.
