### ISSUE TITLE
plugins 1.5 file is missing on the website

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#89]
On the website: https://psi-im.org/download/

We can see:
Source Code
Sources: https://sourceforge.net/projects/psi/files/Psi/1.5/psi-1.5.tar.xz
2.1 MB archive
Requires Qt 4.8 or Qt 5.5+

Translations: https://github.com/psi-im/psi-l10n/archive/1.5.tar.gz
2.9 MB archive
Requires Qt 4.8 or Qt 5.5+

Plugins: https://github.com/psi-im/plugins/archive/1.4.tar.gz
820 KB archive
Requires Qt 4.8 or Qt 5.5+

---------

Note, there are tag problems on GitHub and on the website, it is direct link to GitHub:

2 same builds for plugins:
- https://github.com/psi-im/plugins/archive/1.4.tar.gz
- https://github.com/psi-im/plugins/archive/1.5.tar.gz

2 same builds for psi-l10n:
- https://github.com/psi-im/psi-l10n/archive/1.5.tar.gz
- https://github.com/psi-im/psi-l10n/archive/1.4.tar.gz

Linked to:
- https://github.com/psi-im/plugins/issues/88

Thanks in advance.

**Comment by tehnick** [comment]
> Translations: https://github.com/psi-im/psi-l10n/archive/1.5.tar.gz
> 2.9 MB archive

Link is updated.
